name: sample_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^0.23.0+1
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  http: ^1.2.0
  intl: ^0.19.0
  provider: ^6.1.2
  image_network: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf  
  uses-material-design: true
